name:                robko01
version:             0.1.0.0
github:              "varosi/robko01"
license:             BSD3
author:              "Vassil Keremidchiev"
maintainer:          "varosi@gmail.com"
copyright:           "2019 Vassil Keremidchiev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/robko01#readme>

dependencies:
- base >=4.7 && <5
- serialport >= 0.4.7 && <0.5.0
- bytestring
- attoparsec
- extra

library:
  source-dirs: src

executables:
  robko01-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - robko01

tests:
  robko01-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - robko01
    - hspec
